services:
  - type: web
    name: bitget-autobot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: BITGET_API_KEY
        sync: false
      - key: BITGET_API_SECRET
        sync: false
      - key: BITGET_API_PASSPHRASE
        sync: false
      - key: SECRET_TOKEN
        sync: false
